<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="clz_project._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">


    <div class="mt-5" style="margin-top: 100px">
        <asp:Button Text="add" CssClass="btn btn-primary " style="display:block; margin-left:auto" OnClick="add_student" runat="server" />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false"
            Width="100%" CssClass="table table-bordered" OnRowEditing="GridView1_RowEditing"
            AutoGenerateDeleteButton="true"  OnRowDeleting="GridView1_RowDeleting"
            AutoGenerateEditButton="true"  DataKeyNames="id">
            <Columns>
                <asp:BoundField DataField="id" HeaderText="ID" />
                <asp:BoundField DataField="name" HeaderText="Name" />
                <asp:BoundField DataField="address" HeaderText="Address" />
                <asp:BoundField DataField="faculty" HeaderText="Faculty" />
                <%--<asp:BoundField  HeaderText="actions" />--%>
               <%-- <asp:TemplateField HeaderText="actions">
                    <ItemTemplate>
                        <asp:Button ID="Button1" runat="server" Text="Edit" CommandName="EditButton"  />
                    </ItemTemplate>
                </asp:TemplateField>--%>

            </Columns>
        </asp:GridView>
    </div>

</asp:Content>
